### ISSUE TITLE
[FEATURE] 페이지 별 데이터 조회 (READ) 정리

### ISSUE THREAD

**Issue by chyerin802** [codestates-seb/seb41_main_006#113]
### Description
페이지 별로 데이터 조회가 필요한 로직 정리

### Task list
---  
- [x] 더미데이터 api 문서에 맞게 변수명 수정
- [x] 조회한 각 데이터 화면에 맞게 지정해서 넣기
- [x] 산책 메이트 (유저) 화면은 API 확정 이후 수정 예정

**Comment by chyerin802** [comment]
task done
