### ISSUE TITLE
[FEATURE] 강아지 엔티티 CRUD 구현 

### ISSUE THREAD

**Issue by hiy7030** [codestates-seb/seb41_main_006#17]
# issue: ✅Feature  

### Description
---  
1. 강아지 정보를 등록할 수 있다.
2. 등록된 강아지 정보에 또 다른 강아지의 정보를 추가할 수 있다.
3. 등록한 강아지 정보를 수정할 수 있다.
4.  등록한 강아지 정보를 삭제할 수 있다.
### Task list
---  
- [x] 강아지 엔티티 구현
- [x] 강아지 api handler 구현
- [x] 강아지 DTO 구현
- [x] 강아지 등록, 수정, 삭제 비즈니스 로직 구현
- [x] 강아지 정보를 저장할 데이터 액세스 계층 구현

### ETC
---
기타 사항 작성
후순위
- [x] 또 다른 강아지의 정보를 추가 등록하는 기능
